POST http://localhost:3333/suplemento
Content-Type: application/json

{
   "tipo": "Whey",
   "quantidade": 30,
   "marca": "Growth",
   "preço": 500,
   "peso": 1000,
   "proteina": 24
}

###

GET http://localhost:3333/suplementos

###

GET http://localhost:3333/suplementos?search=Growth

###

PUT http://localhost:3333/suplemento/b6d6070f-66db-4a32-af1c-072d51be0706
Content-Type: application/json

{
   "tipo": "Creatina",
   "quantidade": 25,
   "marca": "Growth",
   "preço": 700,
   "peso": 100,
   "proteina": 5
}

###

DELETE http://localhost:3333/suplemento/fdfeab57-0138-42eb-969f-65bfd0243846

###

PATCH http://localhost:3333/suplemento/6d70d099-5140-4995-90e6-c2c4c8e506b6
Content-Type: application/json

{
   "nome": "Danones e CIA"
}
