POST http://localhost:3333/suplemento
Content-Type: application/json

{
   "tipo": "Whey",
   "quantidade": 30,
   "marca": "Growth",
   "preço": 500,
   "peso": 1000,
   "proteina": 24
}

###

GET http://localhost:3333/suplementos

###

GET http://localhost:3333/suplementos?search=Growth

###

PUT http://localhost:3333/suplemento/5d252630-2293-4276-ba52-12e6f8419944
Content-Type: application/json

{
   "tipo": "Creatina",
   "quantidade": 25,
   "marca": "Growth",
   "preço": 700,
   "peso": 100,
   "proteina": 5
}

###

DELETE http://localhost:3333/suplemento/1b9a49eb-3a00-4eb5-9230-5adb8d204389

###

PATCH http://localhost:3333/suplemento/6d70d099-5140-4995-90e6-c2c4c8e506b6
Content-Type: application/json

{
   "nome": "Danones e CIA"
}
